### ISSUE TITLE
Query all documents across all partitions within one method

### ISSUE THREAD

**Issue by ben790924** [btnguyen2k/gocosmos#14]
Like using cosmos API for Nodejs sdk
```
await client.mycontainer.items.query(...).fetchAll()
```
or I missing something? Thanks

**Comment by btnguyen2k** [comment]
Hi @ben790924,

CosmosDB supports SQL interface. So you can use `SELECT * FROM table_name WITH cross_partition=true`. See more at https://github.com/btnguyen2k/gocosmos/blob/main/SQL.md#select

Cheers,
Thanh

**Comment by btnguyen2k** [comment]
Using the Restclient directly you can see example here: https://github.com/btnguyen2k/gocosmos/blob/cb1293bf551ee3aed45c93a2bbc914e37314ef91/restclient_test.go#L1365

**Comment by ben790924** [comment]
Seems it still has to use loop to check continuation token rather than just one method to retrieve all documents ?
```
for result = client.QueryDocuments(query); result.Error() == nil; {
		totalRu += result.RequestCharge
		documents = append(documents, result.Documents...)
		if result.ContinuationToken == "" {
			break
		}
		query.ContinuationToken = result.ContinuationToken
		result = client.QueryDocuments(query)
	}
```

**Comment by btnguyen2k** [comment]
@ben790924, yes it has to use continuation token. This is documented in Azure CosmosDB doc at https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-pagination

> When query results cannot be returned in one single execution, Azure Cosmos DB will automatically split results into multiple pages.

The server may split the returned documents and that's something client can't control. Not sure what is your concern about it.

**Comment by btnguyen2k** [comment]
Also, this is excerpted from the NodeJS SDK:

> // notice how we're switching to queryIterator.executeNext instead of calling .fetchAll() as before
> // reason being, fetchAll will issue multiple requests to the server until it has fetched all results
> // here we can control this using executeNext.

The fetchAll() method also uses continuation token under the hood.

**Comment by ben790924** [comment]
What if you wrap queryIterator looping and retrieved all docs in client.QueryDocuments method, is it bad idea?

**Comment by ben790924** [comment]
But when I execute ```SELECT MAX(c.number) FROM c```  the result was not what I expected. Maybe I will reproduce this one later.

**Comment by btnguyen2k** [comment]
I suggest you'd better explain what issue you have having or else I am afraid I cant follow you.

**Comment by ben790924** [comment]
@btnguyen2k Thank you for your help
